spring.application.name=Movie_Platform_Backend

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=ana
spring.datasource.password=ana
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port=8081